### PR TITLE
FIX: Optimise PagesWithoutReviewScheduleReport database query

### PR DESCRIPTION
**Pull request by GuySartorelli**
Drastically speeds up report generation on very large sites and reduces the likelyhood of running into memory issues.

### CODE REVIEW

**Comment by GuySartorelli** [comment]
The SilverStripe\ContentReview\Tests\ContentReviewReportTest::testPagesWithoutReviewScheduleReport test is failing so I'll pull this back to draft until I can figure out what's not quite right and resolve it (if anyone has any ideas I'd be happy to hear them)

**Comment by GuySartorelli** [comment]
Okay, so I'm at the stage where I'm not sure if it's the change in logic that is incorrect or if it's that the original logic was flawed.

The test isn't passing because I'm filtering out _every_ page that has a value in `NextReviewDate` and saying those pages _do_ have a review scheduled (and thus excluding them from the report).

However, the `hasReviewSchedule` method is set up such that pages can be considered to not have a review scheduled if _either_ they don't have a value in `NextReviewDate` _or_ they have no `OwnerGroups` or `OwnerUsers`.

It isn't super clear to me which of these is correct. I lean towards the latter being correct but I'm just getting tripped up on the language of "Pages without a scheduled review" - in my mind the review is scheduled whether there is someone assigned to review it or not.

@stojg looking at the commit history you set that up originally, what are your thoughts on this? As I said I'm leaning towards keeping the functionality exactly as you had laid it out but I just want to make sure the original intention was what it appears to be before I update my PR to match.

**Comment by dhensby** [comment]
@stojg - you're the original author of this, any thoughts?

**Comment by stojg** [comment]
wow, 7 year old crimescene. what some nostalgia. This module came about for a specific client that was really really really into having a proper process for every singel piece of content on their website. It is very likely that due to their requirements and organisational idiosyncrasies that I or someone else blended two pieces of different logic under a `hasReviewSchedule` method, which is now confusing for all involved. Ie pages needs to have an owner, otherwise they need to be checked by someone asap.

However I can barely remember what I had for lunch yesterday so I cannot with any confidence claim what the intent was. But I remembered this module being more of MVP to get that client to switch to using SilverStripe, and later got adopted into the CWP supported modules and taken care by a lot more reliable team of developers. I would say, it's confusing, so I personally would
a) create a new method named to something that is more logical and deprecate the current one, however naming is, as always  hard.
b) make it an option (more options ahoy!) to skip the owner check and keep it to do the owner check.
c) burn it all the ground, skip the owner check and release a major version 

As for which process is best, it's probably up to the current supporters to say.

Thanks for this nostalgia trip :)

**Comment by GuySartorelli** [comment]
@dhensby Given Stojg's remarks, how would you like me to proceed?

**Comment by dhensby** [comment]
Good question; I think we need to get the tests passing for one, then we can get it in if it's just a perfomance enhancement. If there's a change of behaviour, we'll need to think about putting it into master.

**Comment by GuySartorelli** [comment]
I'm closing this - I don't have time to work on it and it was mostly problematic for my projects in the main reports gridfield view which can be resolved with silverstripe/silverstripe-reports#139.

**Pull request closed without merging**
