### PR TITLE
Travis 4.1

### PR DESCRIPTION
**Pull request by emteknetnz**
Travis failure is a behat failure, probably unrelated to this PR. 

Issue to cover behat failure raised here: https://github.com/silverstripe/silverstripe-contentreview/issues/128

### CODE REVIEW

**Comment by robbieaverill** [comment]
The last build is green, albeit it was 5 months ago: https://travis-ci.org/github/silverstripe/silverstripe-contentreview/builds/572112498

For some reason I can't re-run it, perhaps you could do that to validate your suggestion that this PR didn't break the behat build.

**Comment by brynwhyman** [comment]
Yeah +1 to double checking whether the failure is actually a result of this PR, or whether if it would fail regardless.

**Comment by brynwhyman** [comment]
Re-running the `4` build: https://travis-ci.org/github/silverstripe/silverstripe-contentreview/builds/701866639 and queued `4.1`: https://travis-ci.org/github/silverstripe/silverstripe-contentreview/builds/701866795

**Comment by brynwhyman** [comment]
Yeah, looks like behat test fails without this PR 😞 . I'd say this is still good to merge?

**Comment by robbieaverill** [comment]
Yep send it, thanks for checking

**Pull request closed without merging**
