### PR TITLE
MNT Add additional keywords to composer.json

### PR DESCRIPTION
**Pull request by sunnysideup**

### CODE REVIEW

**Comment by GuySartorelli** [comment]
I'm generally okay with this - but can you please change the commit message to something more generic? Like
> MNT Add additional keywords to composer.json

**Comment by sunnysideup** [comment]
:-) done

**Comment by GuySartorelli** [comment]
You've changed the name of the PR - but can you please change the actual commit message?
You can do this using `git commit --amend` and the force push to your branch.

Please also use `MNT` instead of `MINOR:` for this change as per [our documentation](https://docs.silverstripe.org/en/4/contributing/code/#commit-messages)

**Comment by sunnysideup** [comment]
ooops. sorry. I will do that.

**Comment by michalkleiner** [comment]
@GuySartorelli fixed. Do you want this against `4`, `5` or `5.0` branch? I can rebase if needed.

**Comment by GuySartorelli** [comment]
This is just changing keywords so it's fine to be included in CMS 4.13 or a future patch release - please target the `4.7` branch.

**Pull request merged**
