### PR TITLE
FIX Ensure QueuedJob health check doesn't kill long running review jobs

### PR DESCRIPTION
**Pull request by silbinarywolf**
FIX Ensure QueuedJob health check doesn't kill long running review jobs

### CODE REVIEW

**Comment by robbieaverill** [comment]
@silbinarywolf if you wouldn't mind rebasing this pull request we can get it merged in. FYI the master branch is now SS4 compat - switch to 3.0 for SS3 bugfixing :)

**Comment by silbinarywolf** [comment]
@robbieaverill This should be all good cap'n!

**Comment by silbinarywolf** [comment]
Hm... FYI Looks like this fix isnt in `master`.
So not sure if you want to cherry pick it across or...?

**Comment by robbieaverill** [comment]
That's OK, it'll get merged up to master eventually

**Pull request merged**
